import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('evidence stays inspectable and requirement changes invalidate matches', async ({ page }) => {
  await page.goto('/?workspace=demo')
  await expect(page.getByRole('heading', { name: 'A few days in London' })).toBeVisible()
  await expect(page.getByText('Hotels, measurements and replies here are fictional.', { exact: false })).toBeVisible()
  const door = page.getByRole('row', { name: /Door clear opening/ })
  await door.getByRole('button').first().click()
  await expect(page.getByRole('dialog')).toContainText('The accessible king bedroom door has a clear opening of 84 cm.')
  await expect(page.getByRole('dialog')).toContainText('Direct confirmation is still pending.')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'Try an example reply' }).click()
  await expect(door.getByRole('button').first()).toContainText('Hotel stated')
  await page.getByRole('button', { name: /^Edit/ }).click()
  await page.getByLabel('Minimum door opening').fill('90')
  await page.getByRole('button', { name: 'Save requirements' }).click()
  await expect(door.getByRole('button').first()).toContainText('Outside your requirement')
})
test('conflicting evidence is shown together and asks for clarification', async ({ page }) => {
  await page.goto('/?workspace=demo')
  const bed = page.getByRole('row', { name: /Mattress height/ })
  await bed.getByRole('button').last().click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('Answers differ')
  await expect(dialog).toContainText('52 cm')
  await expect(dialog).toContainText('62 cm')
  await dialog.getByRole('button', { name: 'Review hotel questions' }).click()
  await expect(page.getByLabel('Message preview')).toHaveValue(/conflicting information/)
  await expect(page.getByRole('button', { name: 'Send unavailable' })).toBeDisabled()
})
test('export carries the example disclosure, uncertainty and original sources', async ({ page }) => {
  await page.goto('/?workspace=demo')
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export brief' }).click()
  const file = await downloaded
  const path = await file.path()
  expect(path).not.toBeNull()
  const text = await readFile(path!, 'utf8')
  expect(text).toContain('ILLUSTRATIVE DEMO')
  expect(text).toContain('Availability: unknown')
  expect(text).toContain('Answers differ')
  expect(text).toContain('2026-09-08')
})
test('new comparisons start without fictional hotel evidence', async ({ page }) => {
  await page.goto('/?workspace=demo')
  await page.getByRole('button', { name: 'New local trip' }).click()
  await page.getByLabel('Trip name').fill('A real shortlist')
  await page.getByLabel('Destination', { exact: true }).fill('London')
  await page.getByLabel('Arrival', { exact: true }).fill('2026-10-12')
  await page.getByLabel('Departure', { exact: true }).fill('2026-10-15')
  await page.getByLabel('Hotel name', { exact: true }).fill('Hotel to investigate')
  await page.getByLabel('Hotel or room page (HTTPS)').fill('https://www.hyatt.com')
  await page.getByLabel('Specific room type').fill('Accessible queen room')
  await page.getByRole('button', { name: 'Create local comparison' }).click()
  await expect(page.getByRole('heading', { name: 'A real shortlist' })).toBeVisible()
  await expect(page.getByRole('row', { name: /Door clear opening/ })).toContainText('Needs an answer')
  await expect(page.getByText('Canal House', { exact: true })).not.toBeVisible()
})
test('mobile comparison is keyboard scrollable without overflowing the whole page', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?workspace=demo')
  const table = page.getByRole('region', { name: /Hotel comparison/ })
  await table.focus()
  await expect(table).toBeFocused()
  const dimensions = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }))
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'artifacts/mobile-comparison.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'artifacts/desktop-comparison.png', fullPage: true })
})
